name: Create Release

on:
  push:
    tags:
      - 'v_*.*.*'  # Matches tags like v_1.0.0.0, v_2.1.3.0, etc.

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Activate virtualenv
        run: |
            . .venv/bin/activate
            echo PATH=$PATH >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        working-directory: ./src
        run: |
          # Run your build script here
          python create_versionfile.py

      - name: Run PowerShell script
        run: |
          pwsh ./createNewTeamsBusyLightExe.ps1

      - name: Read changelog
        id: read_changelog
        run: |
           echo "changelog=$(cat changelog_currentVersion.md)" >> $GITHUB_ENV
        continue-on-error: false

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.changelog }}
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/MS_Teams_Busy_Light.zip
          asset_name: MS_Teams_Busy_Light.zip
          asset_content_type: application/zip
