name: Test Release Package

on:
  push:
    tags:
    #  - 'v_*.*.*'  # Matches tags like v_1.0.0.0, v_2.1.3.0, etc.
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
   Checkout_and_install_dependencies:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repository
         uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.x'

  #     - name: Create virtualenv
  #       run: |
  #           python -m venv .venv
  
  #     - name: Activate virtualenv
  #       run: |
  #           source .venv/bin/activate
  #           echo PATH=$PATH >> $GITHUB_ENV

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  start_pyinstaller:
    steps: 
      - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12.0'
        pyinstaller_ver: '>=6.10.0'
        spec: 'MS_Teams_Busy_Light.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'MS Teams Presence Status Busy Light'
        options: --onefile --icon=$iconFile --version-file="images/traffic_light.ico" --clean --windowed"
              


